'use client';
import { useState } from 'react';
import type { RoomState } from '@/games/core/types';
import { useAiBarenaiGame } from './hooks/useAiBarenaiGame';

interface Props { roomState: RoomState; myUserId: string; onBackToLobby: () => Promise<void> }
export function AiBarenaiGame({roomState, myUserId, onBackToLobby}: Props) {
  const {gameState, topic, handleInitialize, handleHint, handleAnswer, handleNextRound, handleTopic} = useAiBarenaiGame(roomState);
  const [hints, setHints] = useState(gameState.hintsPerRound); const [text, setText] = useState(''); const [error, setError] = useState('');
  const isHost = roomState.host_id === myUserId, isAnswerer = gameState.answererId === myUserId;
  const isAssignee = gameState.currentAssigneeIds.includes(myUserId), submitted = gameState.submittedHintPlayerIds.includes(myUserId);
  const playerName = (id: string | null) => roomState.players.find((player) => player.userId === id)?.name ?? '参加者';
  const assigneeNames = gameState.currentAssigneeIds.map(playerName).join('、');
  const fullOrderNames = gameState.clueGiverOrder.map(playerName).join(' → ');
  const act = async (fn: () => Promise<unknown>) => { setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : '操作に失敗しました'); } };
  if (gameState.phase === 'rule_setting') return <main className="paper-card mx-auto max-w-2xl p-6 sm:p-10"><p className="section-kicker">AI GAME</p><h1 className="mt-2 text-3xl font-black">AIにバレるな！</h1><p className="mt-4 leading-7 text-[var(--muted)]">お題を知らない回答者に、みんなでヒントを出します。AIより先に当てられるか挑戦しましょう。</p>{isHost ? <div className="mt-8"><label className="font-bold">1ラウンドのヒント担当人数</label><input type="number" min={1} max={Math.max(1, roomState.players.length - 1)} value={hints} onChange={e=>setHints(Number(e.target.value))} className="mt-2 block w-32 rounded border-2 border-[var(--line)] bg-white p-3 text-xl font-black" /><button className="button-primary mt-5" onClick={()=>void act(()=>handleInitialize(hints))}>ゲームを始める</button></div> : <p className="mt-8 font-bold text-[var(--muted)]">ホストがルールを設定しています…</p>}<button className="text-link mt-8 block" onClick={()=>void onBackToLobby()}>← ロビーに戻る</button></main>;
  const phaseTitle = gameState.phase === 'hinting' ? 'ヒントを積み上げよう' : gameState.phase === 'answering' ? '回答タイム' : gameState.phase === 'revealing' ? '結果発表' : 'ゲーム終了';
  return <main className="mx-auto max-w-3xl space-y-5"><header className="paper-card p-5 sm:p-7"><div className="flex items-center justify-between"><p className="section-kicker">ROUND {gameState.round}</p><span className="rounded-full bg-[var(--yellow)] px-3 py-1 text-xs font-black">{gameState.phase}</span></div><h1 className="mt-2 text-3xl font-black">{phaseTitle}</h1><p className="mt-2 text-sm font-bold text-[var(--muted)]">回答者：{playerName(gameState.answererId)}</p>{fullOrderNames && <p className="mt-2 text-xs font-bold text-[var(--muted)]">ヒント順：{fullOrderNames}</p>}{isAnswerer ? <p className="mt-3 font-bold text-[var(--orange)]">あなたは回答者です。お題は見ず、ヒントが揃うまで待ちましょう。</p> : (gameState.phase === 'hinting' || gameState.phase === 'answering') && <>{topic ? <p className="mt-3 font-black text-[var(--purple)]">お題：{topic}</p> : <button className="button-secondary mt-3" onClick={()=>void act(handleTopic)}>担当者のお題を確認する</button>}</>}</header>
    {gameState.phase === 'hinting' && <section className="paper-card p-5"><h2 className="text-xl font-black">今回のヒント担当</h2><p className="mt-2 font-bold text-[var(--muted)]">{assigneeNames}</p><p className="mt-2 text-sm text-[var(--muted)]">{isAnswerer ? 'みんながヒントを出すのを待っています。' : isAssignee ? (submitted ? 'このラウンドは提出済みです。' : 'お題を直接言わずにヒントを1つ出してください。') : '今回はヒント担当ではありません。'}</p>{isAssignee && !submitted && <form className="mt-4 flex gap-2" onSubmit={e=>{e.preventDefault(); void act(async()=>{await handleHint(text);setText('')})}}><input value={text} onChange={e=>setText(e.target.value)} maxLength={300} required className="min-w-0 flex-1 rounded border-2 border-[var(--line)] bg-white p-3" placeholder="ヒントを入力"/><button className="button-primary" type="submit">提出</button></form>}<p className="mt-3 text-xs font-bold text-[var(--muted)]">提出済み {gameState.submittedHintPlayerIds.length} / {gameState.currentAssigneeIds.length}</p></section>}
    {gameState.revealedHintHistory.length > 0 && <section className="paper-card p-5"><h2 className="text-xl font-black">公開されたヒント</h2><div className="mt-4 space-y-3">{gameState.revealedHintHistory.map(r=><div key={r.round}><p className="text-xs font-black text-[var(--muted)]">ラウンド {r.round}</p>{r.hints.map(h=><p key={h.playerId} className="mt-1 rounded bg-[var(--surface)] p-3 font-bold">{h.text}</p>)}</div>)}</div></section>}
    {gameState.phase === 'answering' && <section className="paper-card p-5"><p className="font-bold">{isAnswerer ? 'ヒントからお題を一度だけ回答してください。' : 'AIも考えています。回答者の入力を待っています。'}</p>{isAnswerer && !gameState.humanAnswerSubmitted && <form className="mt-4 flex gap-2" onSubmit={e=>{e.preventDefault();void act(async()=>{await handleAnswer(text);setText('')})}}><input value={text} onChange={e=>setText(e.target.value)} required maxLength={200} className="min-w-0 flex-1 rounded border-2 border-[var(--line)] bg-white p-3" placeholder="お題の答え"/><button className="button-primary" type="submit">回答する</button></form>}<p className="mt-3 text-sm text-[var(--muted)]">人間の回答：{gameState.humanAnswerSubmitted?'提出済み':'待機中'} / AI：{gameState.aiGuessReady?'準備完了':'思考中…'}</p></section>}
    {gameState.result && <section className="paper-card p-5"><p className="section-kicker">RESULT</p><h2 className="mt-2 text-3xl font-black">{gameState.phase === 'revealing' ? '両者不正解' : gameState.result.winner === 'ai' ? 'AIの勝利' : '人間の勝利'}</h2>{gameState.result.topic ? <p className="mt-4 font-bold">お題：{gameState.result.topic}</p> : <p className="mt-4 font-bold text-[var(--muted)]">お題は次のラウンドまで秘密です。</p>}<p className="mt-2">人間：{gameState.result.humanAnswer}（{gameState.result.humanCorrect?'正解':'不正解'}）</p><p>AI：{gameState.result.aiError ? 'AI回答を取得できませんでした' : gameState.result.aiAnswer}（確信度 {gameState.result.aiConfidence}%・{gameState.result.aiCorrect?'正解':'不正解'}）</p>{gameState.phase === 'revealing' && <button className="button-primary mt-5" onClick={()=>void act(handleNextRound)}>次のラウンドへ</button>}{gameState.phase === 'game_over' && <button className="text-link mt-5 block" onClick={()=>void onBackToLobby()}>ロビーに戻る</button>}</section>}
    {error && <p className="font-bold text-red-600">{error}</p>}
  </main>;
}
