import 'server-only';

export interface AiBarenaiTopic {
  answer: string;
  aliases: string[];
}

/** Server-only presets. Add one object per topic; multiple aliases are supported. */
export const AI_BARENAI_TOPICS = [
  // Places and landmarks
  { answer: '富士山', aliases: ['ふじさん'] },
  { answer: '東京タワー', aliases: ['とうきょうタワー'] },
  { answer: '東京スカイツリー', aliases: ['スカイツリー'] },
  { answer: '大阪城', aliases: ['おおさか城'] },
  { answer: '北海道', aliases: ['ほっかいどう'] },
  { answer: '沖縄', aliases: ['おきなわ'] },
  { answer: '京都', aliases: ['きょうと'] },
  { answer: 'パリ', aliases: ['Paris'] },
  { answer: 'ニューヨーク', aliases: ['New York', 'NYC'] },
  { answer: '遊園地', aliases: ['テーマパーク'] },
  { answer: '公園', aliases: ['こうえん'] },
  { answer: '学校', aliases: ['がっこう'] },
  { answer: '病院', aliases: ['びょういん'] },
  { answer: 'コンビニ', aliases: ['コンビニエンスストア'] },
  { answer: 'ホテル', aliases: ['宿泊施設'] },
  { answer: '神社', aliases: ['じんじゃ'] },
  { answer: '水族館', aliases: ['すいぞくかん'] },
  { answer: '動物園', aliases: ['どうぶつえん'] },
  { answer: '図書館', aliases: ['としょかん'] },
  { answer: '映画館', aliases: ['シネマ'] },
  { answer: '空港', aliases: ['エアポート'] },
  { answer: '駅', aliases: ['えき'] },
  { answer: '温泉', aliases: ['おんせん'] },
  { answer: 'キャンプ場', aliases: ['キャンプサイト'] },
  { answer: 'スーパーマーケット', aliases: ['スーパー'] },
  { answer: '美術館', aliases: ['アートミュージアム'] },
  { answer: '灯台', aliases: ['とうだい'] },

  // Food
  { answer: 'りんご', aliases: ['林檎', 'リンゴ'] },
  { answer: 'バナナ', aliases: ['banana'] },
  { answer: 'カレーライス', aliases: ['カレー'] },
  { answer: 'ラーメン', aliases: ['らーめん'] },
  { answer: 'おにぎり', aliases: ['おむすび'] },
  { answer: '寿司', aliases: ['すし'] },
  { answer: 'ハンバーガー', aliases: ['バーガー'] },
  { answer: 'ピザ', aliases: ['pizza'] },
  { answer: 'たい焼き', aliases: ['たいやき'] },
  { answer: 'プリン', aliases: ['ぷりん'] },
  { answer: 'ショートケーキ', aliases: ['苺のショートケーキ'] },
  { answer: 'たこ焼き', aliases: ['たこやき'] },
  { answer: 'いちご', aliases: ['苺', 'イチゴ'] },
  { answer: 'みかん', aliases: ['蜜柑', 'ミカン'] },
  { answer: 'ぶどう', aliases: ['葡萄', 'ブドウ'] },
  { answer: 'すいか', aliases: ['西瓜', 'スイカ'] },
  { answer: 'メロン', aliases: ['melon'] },
  { answer: 'パイナップル', aliases: ['パイン'] },
  { answer: 'オムライス', aliases: ['オムレツライス'] },
  { answer: 'うどん', aliases: ['ウドン'] },
  { answer: 'そば', aliases: ['蕎麦'] },
  { answer: '焼きそば', aliases: ['ソース焼きそば'] },
  { answer: '餃子', aliases: ['ぎょうざ', 'ギョーザ'] },
  { answer: 'お好み焼き', aliases: ['おこのみ焼き'] },
  { answer: '唐揚げ', aliases: ['からあげ', '空揚げ'] },
  { answer: '天ぷら', aliases: ['天麩羅', 'てんぷら'] },
  { answer: 'アイスクリーム', aliases: ['アイス'] },
  { answer: 'ドーナツ', aliases: ['donut', 'doughnut'] },
  { answer: 'チョコレート', aliases: ['チョコ'] },
  { answer: 'クッキー', aliases: ['cookie'] },
  { answer: 'かき氷', aliases: ['かきごおり'] },
  { answer: 'ポップコーン', aliases: ['popcorn'] },

  // Animals
  { answer: '猫', aliases: ['ねこ', 'ネコ'] },
  { answer: '犬', aliases: ['いぬ', 'イヌ'] },
  { answer: 'ライオン', aliases: ['獅子'] },
  { answer: 'トラ', aliases: ['虎'] },
  { answer: '象', aliases: ['ぞう', 'ゾウ'] },
  { answer: 'キリン', aliases: ['麒麟'] },
  { answer: 'パンダ', aliases: ['ジャイアントパンダ'] },
  { answer: 'ペンギン', aliases: ['ぺんぎん'] },
  { answer: 'イルカ', aliases: ['海豚'] },
  { answer: 'クジラ', aliases: ['鯨'] },
  { answer: 'うさぎ', aliases: ['兎', 'ウサギ'] },
  { answer: 'カメ', aliases: ['亀'] },
  { answer: 'サル', aliases: ['猿'] },
  { answer: 'キツネ', aliases: ['狐'] },
  { answer: 'たぬき', aliases: ['狸'] },
  { answer: 'フクロウ', aliases: ['梟'] },
  { answer: 'ハチ', aliases: ['蜂'] },
  { answer: 'チョウ', aliases: ['蝶'] },
  { answer: 'カブトムシ', aliases: ['かぶと虫'] },
  { answer: 'コアラ', aliases: ['koala'] },
  { answer: 'カンガルー', aliases: ['kangaroo'] },
  { answer: 'ハリネズミ', aliases: ['針鼠'] },
  { answer: 'リス', aliases: ['栗鼠'] },
  { answer: 'ハムスター', aliases: ['hamster'] },
  { answer: 'ナマケモノ', aliases: ['なまけもの'] },
  { answer: 'ゴリラ', aliases: ['gorilla'] },
  { answer: 'シマウマ', aliases: ['縞馬', 'ゼブラ'] },
  { answer: 'カバ', aliases: ['河馬'] },
  { answer: 'サイ', aliases: ['犀'] },
  { answer: 'オオカミ', aliases: ['狼'] },
  { answer: 'シロクマ', aliases: ['ホッキョクグマ', '白熊'] },
  { answer: 'アザラシ', aliases: ['海豹'] },
  { answer: 'ラッコ', aliases: ['海獪'] },
  { answer: 'タコ', aliases: ['蛸', 'たこ'] },
  { answer: 'クラゲ', aliases: ['水母'] },
  { answer: 'サメ', aliases: ['鮫'] },

  // Characters
  { answer: 'ドラえもん', aliases: [] },
  { answer: 'ピカチュウ', aliases: ['ピカチュー', 'Pikachu'] },
  { answer: 'アンパンマン', aliases: ['あんぱんまん'] },
  { answer: 'マリオ', aliases: ['スーパーマリオ'] },
  { answer: 'モンキー・D・ルフィ', aliases: ['ルフィ'] },
  { answer: '江戸川コナン', aliases: ['コナン', '名探偵コナン'] },
  { answer: 'ミッキーマウス', aliases: ['ミッキー'] },
  { answer: 'ハローキティ', aliases: ['キティちゃん', 'キティ'] },
  { answer: 'トトロ', aliases: ['となりのトトロ'] },
  { answer: 'スヌーピー', aliases: ['Snoopy'] },
  { answer: 'くまのプーさん', aliases: ['プーさん', 'くまのプー'] },
  { answer: 'ヨッシー', aliases: ['Yoshi'] },
  { answer: 'カービィ', aliases: ['星のカービィ'] },
  { answer: 'ちびまる子ちゃん', aliases: ['まる子', 'まるちゃん'] },

  // Activities and games
  { answer: 'サッカー', aliases: ['フットボール'] },
  { answer: '野球', aliases: ['ベースボール'] },
  { answer: 'バスケットボール', aliases: ['バスケ'] },
  { answer: 'テニス', aliases: ['tennis'] },
  { answer: '水泳', aliases: ['スイミング'] },
  { answer: '将棋', aliases: ['しょうぎ'] },
  { answer: 'かくれんぼ', aliases: ['隠れんぼ'] },
  { answer: 'バレーボール', aliases: ['バレー'] },
  { answer: '卓球', aliases: ['ピンポン'] },
  { answer: 'バドミントン', aliases: ['badminton'] },
  { answer: 'ボウリング', aliases: ['ボーリング'] },
  { answer: 'スキー', aliases: ['ski'] },
  { answer: 'サーフィン', aliases: ['サーフィング'] },
  { answer: 'キャンプ', aliases: ['camping'] },
  { answer: '釣り', aliases: ['フィッシング'] },
  { answer: '料理', aliases: ['クッキング'] },
  { answer: '読書', aliases: ['本を読むこと'] },
  { answer: 'カラオケ', aliases: ['karaoke'] },
  { answer: '鬼ごっこ', aliases: ['おにごっこ'] },

  // Objects and vehicles
  { answer: 'スマートフォン', aliases: ['スマホ'] },
  { answer: 'パソコン', aliases: ['PC', 'コンピューター'] },
  { answer: 'テレビ', aliases: ['TV'] },
  { answer: 'カメラ', aliases: ['写真機'] },
  { answer: '時計', aliases: ['とけい'] },
  { answer: '傘', aliases: ['かさ', 'アンブレラ'] },
  { answer: '靴', aliases: ['くつ'] },
  { answer: '帽子', aliases: ['ぼうし'] },
  { answer: '眼鏡', aliases: ['メガネ', 'めがね'] },
  { answer: '自転車', aliases: ['チャリ', 'バイシクル'] },
  { answer: '電車', aliases: ['列車'] },
  { answer: '飛行機', aliases: ['航空機'] },
  { answer: '船', aliases: ['ふね'] },
  { answer: '車', aliases: ['自動車', 'クルマ'] },
  { answer: 'ロボット', aliases: ['robot'] },
  { answer: '冷蔵庫', aliases: ['れいぞうこ'] },
  { answer: '電子レンジ', aliases: ['レンジ'] },
  { answer: '歯ブラシ', aliases: ['はブラシ'] },
  { answer: '鉛筆', aliases: ['えんぴつ'] },
  { answer: '消しゴム', aliases: ['けしごむ'] },
  { answer: '本', aliases: ['書籍', 'book'] },
  { answer: 'タブレット', aliases: ['タブレット端末'] },
  { answer: 'ゲーム機', aliases: ['ゲームコンソール'] },
  { answer: 'リモコン', aliases: ['リモートコントローラー'] },
  { answer: '懐中電灯', aliases: ['フラッシュライト'] },
  { answer: '鍵', aliases: ['かぎ', 'キー'] },
  { answer: '財布', aliases: ['さいふ', 'ウォレット'] },
  { answer: 'リュックサック', aliases: ['リュック', 'バックパック'] },
  { answer: 'スーツケース', aliases: ['キャリーケース'] },
  { answer: '水筒', aliases: ['すいとう', 'マイボトル'] },
  { answer: '箸', aliases: ['はし', 'お箸'] },
  { answer: 'スプーン', aliases: ['spoon'] },
  { answer: 'フライパン', aliases: [] },
  { answer: '掃除機', aliases: ['そうじき', 'クリーナー'] },
  { answer: '洗濯機', aliases: ['せんたくき'] },
  { answer: '扇風機', aliases: ['せんぷうき'] },
  { answer: 'ピアノ', aliases: ['piano'] },
  { answer: 'ギター', aliases: ['guitar'] },

  // Nature
  { answer: '月', aliases: ['つき', 'お月さま'] },
  { answer: '太陽', aliases: ['おひさま'] },
  { answer: '星', aliases: ['ほし'] },
  { answer: '虹', aliases: ['にじ'] },
  { answer: '雪だるま', aliases: ['ゆきだるま'] },
  { answer: '桜', aliases: ['さくら', 'サクラ'] },
  { answer: 'ひまわり', aliases: ['向日葵'] },
  { answer: '海', aliases: ['うみ'] },
  { answer: '山', aliases: ['やま'] },
  { answer: '川', aliases: ['かわ'] },
  { answer: '雲', aliases: ['くも'] },
  { answer: '雷', aliases: ['かみなり', 'サンダー'] },
  { answer: '火山', aliases: ['かざん'] },
  { answer: '滝', aliases: ['たき'] },
  { answer: '砂漠', aliases: ['さばく'] },
  { answer: 'オーロラ', aliases: ['aurora'] },

  // Events and celebrations
  { answer: 'クリスマス', aliases: ['Christmas', 'Xmas'] },
  { answer: 'ハロウィン', aliases: ['Halloween'] },
  { answer: 'お正月', aliases: ['正月'] },
  { answer: '七夕', aliases: ['たなばた'] },
  { answer: '誕生日', aliases: ['バースデー'] },

  // Occupations
  { answer: '消防士', aliases: ['消防隊員'] },
  { answer: 'パイロット', aliases: ['操縦士'] },
  { answer: '宇宙飛行士', aliases: ['アストロノート'] },
] satisfies readonly AiBarenaiTopic[];

export function pickAiBarenaiTopic(random: () => number = Math.random): AiBarenaiTopic {
  const normalizedRandom = Math.max(0, Math.min(0.999999, random()));
  return AI_BARENAI_TOPICS[Math.floor(normalizedRandom * AI_BARENAI_TOPICS.length)];
}
