begin;

create schema if not exists private;

-- Hands, ordered choices, and votes are deliberately kept outside rooms.game_state.
-- No client role has table privileges; the small RPC surface below is the only access.
create table if not exists private.pinch_hint_player_state (
  room_id uuid not null references public.rooms(id) on delete cascade,
  player_id uuid not null,
  hand jsonb not null default '[]'::jsonb,
  selection jsonb,
  vote text check (vote is null or vote in ('yes', 'no')),
  primary key (room_id, player_id)
);
alter table private.pinch_hint_player_state enable row level security;
revoke all on private.pinch_hint_player_state from public, anon, authenticated;

-- BEGIN GENERATED PINCH CONTENT
-- Generated by scripts/generate-pinch-content.mjs from content.json.
create or replace function public.pinch_hint_item_pool()
returns jsonb language sql immutable set search_path = '' as $fn$
  select '[{"id":"banana","name":"バナナ","icon":"🍌"},{"id":"tape","name":"ガムテープ","icon":"🟫"},{"id":"rope","name":"ロープ","icon":"🪢"},{"id":"flashlight","name":"懐中電灯","icon":"🔦"},{"id":"umbrella","name":"折りたたみ傘","icon":"🌂"},{"id":"phone","name":"スマートフォン","icon":"📱"},{"id":"cardboard","name":"段ボール","icon":"📦"},{"id":"bicycle","name":"自転車","icon":"🚲"},{"id":"magnet","name":"強力な磁石","icon":"🧲"},{"id":"mirror","name":"手鏡","icon":"🪞"},{"id":"scarf","name":"長いスカーフ","icon":"🧣"},{"id":"marker","name":"油性ペン","icon":"🖊️"},{"id":"bottle","name":"空のボトル","icon":"🧴"},{"id":"snack","name":"非常食","icon":"🥨"},{"id":"whistle","name":"ホイッスル","icon":"📣"},{"id":"plastic-bag","name":"大きな袋","icon":"🛍️"},{"id":"string","name":"細いひも","icon":"〰️"},{"id":"sunglasses","name":"サングラス","icon":"🕶️"},{"id":"balloon","name":"風船","icon":"🎈"},{"id":"bucket","name":"バケツ","icon":"🪣"},{"id":"towel","name":"大きなタオル","icon":"🧺"},{"id":"spoon","name":"スプーン","icon":"🥄"},{"id":"notebook","name":"白紙のノート","icon":"📓"},{"id":"bell","name":"小さな鈴","icon":"🔔"},{"id":"fan","name":"うちわ","icon":"🪭"},{"id":"brush","name":"絵の具と筆","icon":"🖌️"},{"id":"soap","name":"せっけん","icon":"🧼"},{"id":"socks","name":"厚手の靴下","icon":"🧦"},{"id":"coin","name":"コイン","icon":"🪙"},{"id":"cushion","name":"ふかふかのクッション","icon":"🛋️"},{"id":"toy-car","name":"ラジコンカー","icon":"🏎️"},{"id":"net","name":"虫取り網","icon":"🥅"},{"id":"ruler","name":"長い定規","icon":"📏"},{"id":"gloves","name":"作業用手袋","icon":"🧤"},{"id":"pot","name":"ふた付きの鍋","icon":"🍲"},{"id":"ladder","name":"小さなはしご","icon":"🪜"},{"id":"clock","name":"目覚まし時計","icon":"⏰"},{"id":"seed","name":"花の種","icon":"🌱"},{"id":"bubble","name":"シャボン玉セット","icon":"🫧"},{"id":"harmonica","name":"ハーモニカ","icon":"🎵"}]'::jsonb;
$fn$;

create or replace function public.pinch_hint_topic_pool()
returns text[] language sql immutable set search_path = '' as $fn$
  select ARRAY[
    '家を出た直後、鍵を部屋の中に置いてきたと気づいた',
    '電車に乗ったあと、財布を家に忘れたと気づいた',
    '提出期限の直前なのに課題ファイルが開かない',
    '無人島で目を覚まし、遠くに船の影が見える',
    '洞窟の中で出口が分からなくなった',
    '大事な発表の直前にマイクが動かなくなった',
    '旅行先でスマートフォンの電池が残り3パーセントになった',
    '雨の帰り道、傘が壊れて靴までびしょ濡れになった',
    '知らない街で集合場所への地図が読めなくなった',
    '朝起きたら目覚ましが鳴らず、出発まであと10分だった',
    'キャンプ場で食料を入れた袋が見つからない',
    '料理の途中でコンロの火がつかなくなった',
    '夜の公園で帰り道を照らすものがなくなった',
    'オンライン会議の直前に部屋の照明が切れた',
    '大切な贈り物を渡す直前に包装が破れてしまった',
    '文化祭の看板が強風で飛ばされてしまった',
    '水族館で友達とはぐれ、館内放送も聞こえない',
    '山道で靴ひもが切れ、歩き続ける必要がある',
    '急な引っ越しで段ボールが一箱だけ足りない',
    '帰宅したら玄関の前に大きな荷物が置かれていた',
    '駅のロッカーが開かず、出発時刻が迫っている',
    '海辺で服が濡れ、バスの時間までに乾かしたい',
    '屋外の受付で参加者リストが風に飛ばされ、木に引っかかった',
    '買い物中に友達とはぐれ、携帯電話も圏外になった',
    '夕食を作ったら辛すぎて、家族がひと口で水を飲み始めた',
    '停電した部屋で、明日の旅行に必要な物を探さなくてはいけない',
    '遠足の集合直前に靴底がはがれ、歩くたびに音がする',
    '公園で鍵を拾ったが、持ち主らしい人はもう見当たらない',
    '引っ越し初日、猫が部屋のどこかに隠れてごはんの時間にも出てこない',
    '急な来客まであと5分なのに、床一面に洗濯物が広がっている',
    '友達の誕生日ケーキが運ぶ途中で傾き、お祝いまであと10分になった',
    '屋外ライブの開場直前、チケットが水たまりに落ちてしまった',
    '図書館で借りた本の間に大切な写真を挟んだまま返してしまった',
    'お店の行列に並んでいると、頭の上から雨漏りが始まった',
    '運動会の司会を頼まれたが、進行表の文字が雨でにじんでしまった',
    '合宿の朝、みんなを起こす係なのに声がかすれて出ない',
    'バザーのお店を任されたが、お釣り用の小銭がなくなった',
    'ピクニックの途中で食べ物にアリが集まってきた',
    '山頂で集合写真を撮りたいが、全員が写るようにカメラを置ける場所がない',
    '家の窓を開けたら大きな虫が入り、天井から降りてこなくなった'
  ];
$fn$;

revoke all on function public.pinch_hint_item_pool() from public, anon, authenticated;
revoke all on function public.pinch_hint_topic_pool() from public, anon, authenticated;
-- END GENERATED PINCH CONTENT

create or replace function public.pinch_hint_is_member(p_room_id uuid, p_actor_id uuid)
returns boolean language sql stable security definer set search_path = '' as $fn$
  select exists (
    select 1 from public.rooms room
    where room.id = p_room_id and (room.host_id = p_actor_id or exists (
      select 1 from pg_catalog.jsonb_array_elements(case when pg_catalog.jsonb_typeof(room.players) = 'array' then room.players else '[]'::jsonb end) player
      where player ->> 'userId' = p_actor_id::text
    ))
  );
$fn$;

create or replace function public.pinch_hint_draw_hand(p_pool jsonb, p_excluded jsonb default '[]'::jsonb, p_count integer default 3)
returns jsonb language sql volatile set search_path = '' as $fn$
  select coalesce((select pg_catalog.jsonb_agg(item)
    from (select item from pg_catalog.jsonb_array_elements(p_pool) item
      where not exists (select 1 from pg_catalog.jsonb_array_elements(p_excluded) old_item where old_item ->> 'id' = item ->> 'id')
      order by pg_catalog.random() limit p_count) drawn), '[]'::jsonb);
$fn$;

create or replace function public.pinch_hint_initialize(p_room_id uuid, p_rounds integer)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare
  actor uuid := (select auth.uid()); r public.rooms%rowtype; state jsonb; ids text[]; scores jsonb;
  pool jsonb := public.pinch_hint_item_pool(); topics text[] := public.pinch_hint_topic_pool(); player_entry jsonb; hand jsonb;
begin
  if actor is null or p_rounds is null or p_rounds not between 1 and 3 then raise exception 'ラウンド数は1〜3で指定してください'; end if;
  select * into r from public.rooms where id = p_room_id for update;
  if not found or r.game_type <> 'pinch-hint' or r.status <> 'playing' or r.host_id <> actor then raise exception 'ホストだけがピンチにひらめきを開始できます'; end if;
  if pg_catalog.jsonb_typeof(r.players) <> 'array' or pg_catalog.jsonb_array_length(r.players) not between 2 and 10 then raise exception '2〜10人で遊んでください'; end if;
  if r.game_state is not null and r.game_state <> '{}'::jsonb and r.game_state ->> 'phase' is distinct from 'rule_setting' then raise exception 'このゲームはすでに開始しています'; end if;
  select pg_catalog.array_agg(entry.value ->> 'userId' order by pg_catalog.random()) into ids from pg_catalog.jsonb_array_elements(r.players) as entry(value);
  if (select count(distinct id) from pg_catalog.unnest(ids) id) <> pg_catalog.cardinality(ids)
    or not (actor::text = any(ids)) then raise exception '参加プレイヤーを確認してください'; end if;
  select pg_catalog.jsonb_object_agg(id, 0) into scores from pg_catalog.unnest(ids) id;
  state := pg_catalog.jsonb_build_object('game','pinch-hint','version',1,'matchId',gen_random_uuid()::text,'stateRevision',0,'phase','turn_setup','rounds',p_rounds,'round',1,'turnIndex',0,
    'totalTurns',pg_catalog.array_length(ids,1) * p_rounds,'turnOrder',to_jsonb(ids),'currentPlayerId',ids[1],
    'topic',topics[1 + pg_catalog.floor(pg_catalog.random() * pg_catalog.array_length(topics,1))::integer],
    'requiredCount',1 + pg_catalog.floor(pg_catalog.random() * 3)::integer,'revealedItems','[]'::jsonb,'votedPlayerIds','[]'::jsonb,'scores',scores,'result',null);
  state := state || pg_catalog.jsonb_build_object('usedTopics',pg_catalog.jsonb_build_array(state->>'topic'));
  delete from private.pinch_hint_player_state where room_id = p_room_id;
  for player_entry in select entry.value from pg_catalog.jsonb_array_elements(r.players) as entry(value) loop
    hand := public.pinch_hint_draw_hand(pool);
    insert into private.pinch_hint_player_state(room_id, player_id, hand, selection, vote)
      values(p_room_id, (player_entry ->> 'userId')::uuid, hand, null, null)
      on conflict(room_id, player_id) do update set hand=excluded.hand, selection=null, vote=null;
  end loop;
  update public.rooms set game_state = state where id = p_room_id;
  return state;
end;
$fn$;

create or replace function public.pinch_hint_get_private(p_room_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare actor uuid := (select auth.uid()); result jsonb; r public.rooms%rowtype;
begin
  select * into r from public.rooms where id=p_room_id for share;
  if actor is null or not public.pinch_hint_is_member(p_room_id, actor)
    or r.game_type is distinct from 'pinch-hint' or r.status is distinct from 'playing'
    then raise exception 'ルームの参加者だけが手札を取得できます'; end if;
  select pg_catalog.jsonb_build_object('hand', ps.hand, 'selection', ps.selection, 'vote', ps.vote) into result
    from private.pinch_hint_player_state ps where room_id=p_room_id and player_id=actor;
  return coalesce(result, pg_catalog.jsonb_build_object('hand','[]'::jsonb,'selection',null,'vote',null))
    || pg_catalog.jsonb_build_object('matchId',r.game_state->>'matchId','turnIndex',r.game_state->'turnIndex','stateRevision',r.game_state->'stateRevision');
end;
$fn$;

create or replace function public.pinch_hint_prepare(p_room_id uuid, p_selection text[], p_expected_turn_index integer, p_expected_match_id text)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare actor uuid := (select auth.uid()); r public.rooms%rowtype; state jsonb; hand jsonb; item_id text; distinct_count integer;
begin
  select * into r from public.rooms where id=p_room_id for update; state:=r.game_state;
  if actor is null or p_expected_match_id is null or state->>'matchId' is distinct from p_expected_match_id or state->>'game' is distinct from 'pinch-hint' or not public.pinch_hint_is_member(p_room_id,actor) or r.game_type is distinct from 'pinch-hint' or r.status is distinct from 'playing' or state->>'game' is distinct from 'pinch-hint' or state->>'phase' is distinct from 'turn_setup' or state->>'currentPlayerId' is distinct from actor::text or (state->>'turnIndex')::integer is distinct from p_expected_turn_index then raise exception 'いまはこのプレイヤーの準備時間ではありません'; end if;
  select player_state.hand into hand from private.pinch_hint_player_state player_state where room_id=p_room_id and player_id=actor for update;
  if p_selection is null or pg_catalog.array_ndims(p_selection) is distinct from 1 or pg_catalog.cardinality(p_selection) <> (state->>'requiredCount')::integer then raise exception '指定された枚数のアイテムを選んでください'; end if;
  select count(distinct value) into distinct_count from pg_catalog.unnest(p_selection) value;
  if distinct_count <> pg_catalog.cardinality(p_selection) then raise exception '同じアイテムは一度だけ選べます'; end if;
  foreach item_id in array p_selection loop
    if not exists (select 1 from pg_catalog.jsonb_array_elements(hand) item where item->>'id'=item_id) then raise exception '手札にないアイテムは選べません'; end if;
  end loop;
  update private.pinch_hint_player_state set selection=to_jsonb(p_selection), vote=null where room_id=p_room_id and player_id=actor;
  state:=state || pg_catalog.jsonb_build_object('phase','presenting','revealedItems','[]'::jsonb,'votedPlayerIds','[]'::jsonb,'result',null);
  state:=state || pg_catalog.jsonb_build_object('stateRevision',coalesce((state->>'stateRevision')::integer,0)+1);
  update public.rooms set game_state=state where id=p_room_id; return state;
end;
$fn$;

create or replace function public.pinch_hint_reveal(p_room_id uuid, p_expected_turn_index integer, p_expected_index integer, p_expected_match_id text)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare actor uuid := (select auth.uid()); r public.rooms%rowtype; state jsonb; private_state private.pinch_hint_player_state%rowtype; item jsonb; item_id text;
begin
  select * into r from public.rooms where id=p_room_id for update; state:=r.game_state;
  if actor is null or p_expected_match_id is null or state->>'matchId' is distinct from p_expected_match_id or state->>'game' is distinct from 'pinch-hint' or not public.pinch_hint_is_member(p_room_id,actor) or r.game_type is distinct from 'pinch-hint' or r.status is distinct from 'playing' or state->>'phase' is distinct from 'presenting' or state->>'currentPlayerId' is distinct from actor::text or (state->>'turnIndex')::integer is distinct from p_expected_turn_index or p_expected_index is distinct from pg_catalog.jsonb_array_length(state->'revealedItems') then raise exception '次のアイテムを公開できません'; end if;
  if p_expected_index < 0 or p_expected_index >= (state->>'requiredCount')::integer then raise exception '公開できるアイテムがありません'; end if;
  select * into private_state from private.pinch_hint_player_state where room_id=p_room_id and player_id=actor for update;
  item_id := private_state.selection ->> p_expected_index;
  select candidate into item from pg_catalog.jsonb_array_elements(private_state.hand) candidate where candidate->>'id'=item_id;
  if item is null then raise exception '選択したアイテムが見つかりません'; end if;
  item := item || pg_catalog.jsonb_build_object('revealedAt',p_expected_index);
  state:=pg_catalog.jsonb_set(state,'{revealedItems}',state->'revealedItems' || pg_catalog.jsonb_build_array(item));
  state:=state || pg_catalog.jsonb_build_object('stateRevision',coalesce((state->>'stateRevision')::integer,0)+1);
  update public.rooms set game_state=state where id=p_room_id; return state;
end;
$fn$;

create or replace function public.pinch_hint_finish_presentation(p_room_id uuid, p_expected_turn_index integer, p_expected_match_id text)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare actor uuid := (select auth.uid()); r public.rooms%rowtype; state jsonb;
begin
  select * into r from public.rooms where id=p_room_id for update; state:=r.game_state;
  if actor is null or p_expected_match_id is null or state->>'matchId' is distinct from p_expected_match_id or state->>'game' is distinct from 'pinch-hint' or not public.pinch_hint_is_member(p_room_id,actor) or r.game_type is distinct from 'pinch-hint' or r.status is distinct from 'playing' or state->>'phase' is distinct from 'presenting' or state->>'currentPlayerId' is distinct from actor::text or (state->>'turnIndex')::integer is distinct from p_expected_turn_index or pg_catalog.jsonb_array_length(state->'revealedItems') <> (state->>'requiredCount')::integer then raise exception 'すべてのアイテムを公開してから終了してください'; end if;
  state:=state || pg_catalog.jsonb_build_object('phase','voting','votedPlayerIds','[]'::jsonb,'result',null,'stateRevision',coalesce((state->>'stateRevision')::integer,0)+1);
  update public.rooms set game_state=state where id=p_room_id; return state;
end;
$fn$;

create or replace function public.pinch_hint_vote(p_room_id uuid, p_expected_turn_index integer, p_vote text, p_expected_match_id text)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare actor uuid := (select auth.uid()); r public.rooms%rowtype; state jsonb; current_id uuid; expected integer; yes_count integer; no_count integer; voted_count integer; success boolean; current_private private.pinch_hint_player_state%rowtype; remaining jsonb; refill jsonb; new_hand jsonb; selection_ids text[]; scores jsonb;
begin
  select * into r from public.rooms where id=p_room_id for update; state:=r.game_state; current_id:=(state->>'currentPlayerId')::uuid;
  if actor is null or p_expected_match_id is null or state->>'matchId' is distinct from p_expected_match_id or state->>'game' is distinct from 'pinch-hint' or p_vote is null or p_vote not in ('yes','no') or not public.pinch_hint_is_member(p_room_id,actor) or r.game_type is distinct from 'pinch-hint' or r.status is distinct from 'playing' or state->>'phase' is distinct from 'voting' or actor = current_id or (state->>'turnIndex')::integer is distinct from p_expected_turn_index then raise exception 'いまは投票できません'; end if;
  select * into current_private from private.pinch_hint_player_state where room_id=p_room_id and player_id=current_id for update;
  if exists(select 1 from private.pinch_hint_player_state where room_id=p_room_id and player_id=actor and vote is not null) then raise exception '投票は一度だけです'; end if;
  if not (state->'turnOrder' ? actor::text) then raise exception 'このゲームの参加者だけが投票できます'; end if;
  update private.pinch_hint_player_state set vote=p_vote where room_id=p_room_id and player_id=actor;
  if not found then raise exception 'プレイヤーの手札が見つかりません'; end if;
  select count(*) filter (where vote='yes'), count(*) filter (where vote='no'), count(*) into yes_count,no_count,voted_count
    from private.pinch_hint_player_state where room_id=p_room_id and player_id in (select (value)::uuid from pg_catalog.jsonb_array_elements_text(state->'turnOrder')) and player_id <> current_id and vote is not null;
  state:=pg_catalog.jsonb_set(state,'{votedPlayerIds}',coalesce(state->'votedPlayerIds','[]'::jsonb) || pg_catalog.jsonb_build_array(actor::text));
  expected:=pg_catalog.jsonb_array_length(state->'turnOrder')-1;
  if voted_count < expected then
    state:=state || pg_catalog.jsonb_build_object('stateRevision',coalesce((state->>'stateRevision')::integer,0)+1);
    update public.rooms set game_state=state where id=p_room_id; return state;
  end if;
  success:=yes_count > no_count;
  scores:=state->'scores';
  if success then scores:=pg_catalog.jsonb_set(scores,ARRAY[current_id::text],to_jsonb(coalesce((scores->>current_id::text)::integer,0)+1),true); end if;
  selection_ids:=array(select value from pg_catalog.jsonb_array_elements_text(current_private.selection) value);
  select coalesce(pg_catalog.jsonb_agg(item), '[]'::jsonb) into remaining from pg_catalog.jsonb_array_elements(current_private.hand) item where not exists(select 1 from pg_catalog.unnest(selection_ids) used where used=item->>'id');
  refill:=public.pinch_hint_draw_hand(public.pinch_hint_item_pool(),current_private.hand,(state->>'requiredCount')::integer);
  new_hand:=remaining || refill;
  update private.pinch_hint_player_state set hand=new_hand,selection=null,vote=null where room_id=p_room_id and player_id=current_id;
  state:=state || pg_catalog.jsonb_build_object('phase','result','scores',scores,'result',pg_catalog.jsonb_build_object('success',success,'yes',yes_count,'no',no_count,'playerId',current_id::text),'stateRevision',coalesce((state->>'stateRevision')::integer,0)+1);
  update public.rooms set game_state=state where id=p_room_id; return state;
end;
$fn$;

create or replace function public.pinch_hint_next_turn(p_room_id uuid, p_expected_turn_index integer, p_expected_match_id text)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare actor uuid := (select auth.uid()); r public.rooms%rowtype; state jsonb; ids jsonb; next_index integer; players_per_round integer; topics text[]:=public.pinch_hint_topic_pool();
begin
  select * into r from public.rooms where id=p_room_id for update; state:=r.game_state;
  if actor is null or p_expected_match_id is null or state->>'matchId' is distinct from p_expected_match_id or state->>'game' is distinct from 'pinch-hint' or r.host_id is distinct from actor or r.game_type is distinct from 'pinch-hint' or r.status is distinct from 'playing' or state->>'phase' is distinct from 'result' or (state->>'turnIndex')::integer is distinct from p_expected_turn_index then raise exception 'ホストだけが次のターンへ進めます'; end if;
  ids:=state->'turnOrder'; next_index:=(state->>'turnIndex')::integer+1; players_per_round:=pg_catalog.jsonb_array_length(ids);
  update private.pinch_hint_player_state set vote=null where room_id=p_room_id;
  if next_index >= (state->>'totalTurns')::integer then state:=state || pg_catalog.jsonb_build_object('phase','finished','currentPlayerId',null,'revealedItems','[]'::jsonb); else
    topics := ARRAY(select topic from pg_catalog.unnest(topics) topic
      where not (coalesce(state->'usedTopics','[]'::jsonb) ? topic));
    state:=state || pg_catalog.jsonb_build_object('phase','turn_setup','turnIndex',next_index,'round',1 + (next_index / players_per_round), 'currentPlayerId',ids->>(next_index % players_per_round),
      'topic',topics[1 + pg_catalog.floor(pg_catalog.random() * pg_catalog.array_length(topics,1))::integer], 'requiredCount',1 + pg_catalog.floor(pg_catalog.random()*3)::integer,'revealedItems','[]'::jsonb,'votedPlayerIds','[]'::jsonb,'result',null);
    state := state || pg_catalog.jsonb_build_object('usedTopics',state->'usedTopics' || pg_catalog.jsonb_build_array(state->>'topic'));
  end if;
  state:=state || pg_catalog.jsonb_build_object('stateRevision',coalesce((state->>'stateRevision')::integer,0)+1);
  update public.rooms set game_state=state where id=p_room_id; return state;
end;
$fn$;

create or replace function public.reject_pinch_hint_direct_state_update()
returns trigger language plpgsql set search_path = '' as $fn$
begin
  -- Keep the starting roster even if a generic leave/kick RPC is called while
  -- a phone is disconnected. Returning to the lobby unlocks membership changes.
  if old.game_type = 'pinch-hint' and old.status = 'playing'
    and old.game_state->>'matchId' is not null and new.status <> 'waiting' then
    if new.game_type is distinct from old.game_type or
      (select pg_catalog.jsonb_agg(p->>'userId' order by p->>'userId') from pg_catalog.jsonb_array_elements(new.players) p)
      is distinct from
      (select pg_catalog.jsonb_agg(p->>'userId' order by p->>'userId') from pg_catalog.jsonb_array_elements(old.players) p)
      then raise exception '進行中の参加者は変更できません。先にロビーへ戻ってください'; end if;
  end if;
  if current_user='authenticated' and (old.game_type='pinch-hint' or new.game_type='pinch-hint')
    and new.game_state is distinct from old.game_state
    and not (new.status='waiting' and new.game_state='{}'::jsonb)
    then raise exception 'ピンチにひらめき！の状態はサーバー操作でのみ変更できます'; end if;
  return new;
end;
$fn$;
drop trigger if exists reject_pinch_hint_direct_state_update_trigger on public.rooms;
create trigger reject_pinch_hint_direct_state_update_trigger before update on public.rooms for each row execute function public.reject_pinch_hint_direct_state_update();

-- Keep the existing start guard aware of this game.
create or replace function public.enforce_game_player_count_on_start()
returns trigger language plpgsql set search_path = '' as $fn$
declare player_count integer; min_players integer; max_players integer; game_name text;
begin
  if new.status <> 'playing' or old.status = 'playing' then return new; end if;
  player_count:=case when pg_catalog.jsonb_typeof(new.players)='array' then pg_catalog.jsonb_array_length(new.players) else 0 end;
  case new.game_type
    when 'fake-artist' then min_players:=3; max_players:=10; game_name:='エセ芸術家';
    when 'coyote' then min_players:=2; max_players:=10; game_name:='Coyote';
    when 'ito' then min_players:=2; max_players:=14; game_name:='ito';
    when 'ai-barenai' then min_players:=2; max_players:=14; game_name:='AIにバレるな！';
    when 'ai-barenai-drawing' then min_players:=2; max_players:=14; game_name:='AIにバレるな！お絵かき版';
    when 'pinch-hint' then min_players:=2; max_players:=10; game_name:='ピンチにひらめき！';
    else return new;
  end case;
  if player_count < min_players or player_count > max_players then raise exception '%は%〜%人で遊べます（現在%人です）',game_name,min_players,max_players,player_count; end if;
  return new;
end; $fn$;
drop trigger if exists enforce_game_player_count_on_start_trigger on public.rooms;
create trigger enforce_game_player_count_on_start_trigger before update of status on public.rooms for each row execute function public.enforce_game_player_count_on_start();

revoke all on function public.pinch_hint_item_pool() from public, anon, authenticated;
revoke all on function public.pinch_hint_topic_pool() from public, anon, authenticated;
revoke all on function public.pinch_hint_is_member(uuid,uuid) from public, anon, authenticated;
revoke all on function public.pinch_hint_draw_hand(jsonb,jsonb,integer) from public, anon, authenticated;
revoke all on function public.pinch_hint_initialize(uuid,integer) from public, anon, authenticated;
revoke all on function public.pinch_hint_get_private(uuid) from public, anon, authenticated;
revoke all on function public.pinch_hint_prepare(uuid,text[],integer,text) from public, anon, authenticated;
revoke all on function public.pinch_hint_reveal(uuid,integer,integer,text) from public, anon, authenticated;
revoke all on function public.pinch_hint_finish_presentation(uuid,integer,text) from public, anon, authenticated;
revoke all on function public.pinch_hint_vote(uuid,integer,text,text) from public, anon, authenticated;
revoke all on function public.pinch_hint_next_turn(uuid,integer,text) from public, anon, authenticated;
grant execute on function public.pinch_hint_initialize(uuid,integer) to authenticated;
grant execute on function public.pinch_hint_get_private(uuid) to authenticated;
grant execute on function public.pinch_hint_prepare(uuid,text[],integer,text) to authenticated;
grant execute on function public.pinch_hint_reveal(uuid,integer,integer,text) to authenticated;
grant execute on function public.pinch_hint_finish_presentation(uuid,integer,text) to authenticated;
grant execute on function public.pinch_hint_vote(uuid,integer,text,text) to authenticated;
grant execute on function public.pinch_hint_next_turn(uuid,integer,text) to authenticated;
revoke execute on function public.reject_pinch_hint_direct_state_update() from public,anon,authenticated,service_role;

commit;
